dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
	path('',views.mahasiswa_list,name='mahasiswa-list'),
	path('mahasiswa/add/',views.mahasiswa_tambah,name='mahasiswa-tambah'),
	path('mahasiswa/<int:nim_mahasiswa>/delete/',views.mahasiswa_hapus,name='mahasiswa-hapus'),
	path('mahasiswa/<int:nim_mahasiswa>/update/',views.mahasiswa_ubah,name='mahasiswa-ubah'),
	path('mahasiswa/cari/hasil',views.mahasiswa_cari,name='mahasiswa-cari'),
]

main/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',RedirectView.as_view(pattern_name='login')),

    # login dan logout
    path('login/',views.do_login,name='login'),
    path('logout/',views.do_logout,name='logout'),

    # dashboard app url
    path('dashboard/',include('dashboard.urls')),
]

dashboard/models.py
from django.db import models

class Mahasiswa(models.Model):
	nim = models.IntegerField(primary_key=True)
	nama = models.CharField(max_length=100)
	jenis_kelamin = models.CharField(max_length=2,choices = (
		('L','Laki-laki'),
		('P','Perempuan'),
	),default=None)
	tempat_lahir = models.CharField(max_length=100)
	tanggal_lahir = models.DateField()
	agama = models.CharField(max_length=10,choices = (
		('islam','Islam'),
		('kristen','Kristen'),
		('protestan','Protestan'),
		('budha','Budha'),
		('hindu','Hindu'),
	),default=None)

	alamat = models.TextField()

	def __str__(self):
		return f"{self.nim}: {self.nama}"

dashboard/forms.py
from django import forms
from .models import Mahasiswa

class MahasiswaForm(forms.ModelForm):
	class Meta:
		model = Mahasiswa

		fields = '__all__'

		widgets = {
			'nim':forms.NumberInput(attrs={'placeholder':'Nim Mahasiswa'}),
			'nama':forms.TextInput(attrs={'placeholder':'Nama Mahasiswa'}),
			'jenis_kelamin':forms.Select(),
			'tempat_lahir':forms.TextInput(attrs={'placeholder':'Tempat Lahir'}),
			'tanggal_lahir':forms.DateInput(attrs={'type':'date'}),
			'agama':forms.Select(),
			'alamat':forms.Textarea(attrs={'placeholder':'Alamat'}),


		}

dashboard/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Mahasiswa
from .forms import MahasiswaForm
from django.db.models import Q

from django.http import JsonResponse
from django.template.loader import render_to_string

def mahasiswa_list(request):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		mahasiswa_list = Mahasiswa.objects.all().order_by('nama')
		return render(request,'dashboard/mahasiswa_list.html',{'mahasiswa_list':mahasiswa_list,'title':'List Mahasiswa'})
	else:
		return redirect('login')

def mahasiswa_cari(request):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		if request.method == 'GET':
			cari = request.GET['cari']
			mahasiswa_list = Mahasiswa.objects.filter(Q(nim__contains=cari)|Q(nama__contains=cari)|Q(alamat__contains=cari))
			banyak_data = mahasiswa_list.count()
			if banyak_data != 0:
				banyak_data = banyak_data
			else:
				banyak_data = 'tidak ada data'
			context = {
				'mahasiswa_list':mahasiswa_list,
				'banyak_data':banyak_data,
				'title':'List Mahasiswa',
			}
			return render(request,'dashboard/mahasiswa_list.html',context)
		
	else:
		return redirect('login')

def mahasiswa_form_save(request,form,template_name):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		data = dict()
		if request.method == 'POST':
			if form.is_valid():
				form.save()
				data['form_is_valid'] = True
				mahasiswa_list = Mahasiswa.objects.all().order_by('nama')
				data['html_mahasiswa_list'] = render_to_string('dashboard/includes/partial_mahasiswa_list.html', {
	                'mahasiswa_list': mahasiswa_list
	            })
			else:
				data['form_is_valid'] = False
		context = {'form': form}
		data['html_form'] = render_to_string(template_name, context, request=request)
		return JsonResponse(data)
	else:
		return redirect('login')


def mahasiswa_tambah(request):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		if request.method == 'POST':
			form = MahasiswaForm(request.POST)
		else:
			form = MahasiswaForm()
		return mahasiswa_form_save(request, form, 'dashboard/includes/partial_mahasiswa_tambah.html')
	else:
		return redirect('login')


def mahasiswa_ubah(request,nim_mahasiswa):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		mahasiswa = get_object_or_404(Mahasiswa,nim=nim_mahasiswa)
		if request.method == "POST":
			form = MahasiswaForm(request.POST,instance=mahasiswa)
		else:
			form = MahasiswaForm(instance=mahasiswa)
		return mahasiswa_form_save(request,form,'dashboard/includes/partial_mahasiswa_ubah.html')
	else:
		return redirect('login')




def mahasiswa_hapus(request,nim_mahasiswa):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		mahasiswa = get_object_or_404(Mahasiswa,nim=nim_mahasiswa)
		data = dict()
		if request.method == "POST":
			mahasiswa.delete()
			data['form_is_valid'] = True
			mahasiswa_list = Mahasiswa.objects.all().order_by('nama')
			data['html_mahasiswa_list'] = render_to_string('dashboard/includes/partial_mahasiswa_list.html',{
				'mahasiswa_list':mahasiswa_list
			})
		else :
			context = {
				'mahasiswa':mahasiswa
			}
			data['html_form'] = render_to_string('dashboard/includes/partial_mahasiswa_hapus.html',context,request=request)
		return JsonResponse(data)
	else:
		return redirect('login')

main/views.py
from django.shortcuts import render,redirect
from django.contrib import auth,messages

def do_login(request):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		return redirect('dashboard:mahasiswa-list')
	
	context ={
		'title':'Login',			
	}

	if request.method == "POST":
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = auth.authenticate(username=username,password=password)

		if user is not None:
			request.session.set_expiry(3600) # set session 5 menit (5x60)
			auth.login(request,user)
			return redirect('dashboard:mahasiswa-list')
		else:
			messages.error(request,"incorrect username or password")

	return render(request,'login.html',context)


def do_logout(request):
	if request.user.is_authenticated and request.user.groups.filter(name='administrator').exists:
		auth.logout(request)
		messages.success(request,'Logout Success')
		return redirect('login')
	else:
		return redirect('login')

dashboard/templates/dashboard/includes/partial_mahasiswa_form.html
{% load widget_tweaks %}
 {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}

dashboard/templates/dashboard/includes/partial_mahasiswa_hapus.html
<form method="post" action="{% url 'dashboard:mahasiswa-hapus' mahasiswa.nim %}" class="js-mahasiswa-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Konfirmasi Hapus Mahasiswa</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Apakah kau yakin menghapus mahasiswa dengan Nim<strong>{{ mahasiswa.nim }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Hapus Mahasiswa</button>
  </div>
</form>

dashboard/templates/dashboard/includes/partial_mahasiswa_list.html
{% for mahasiswa in mahasiswa_list %}
	<tr>
		<td>{{ mahasiswa.nim }}</td>
		<td>{{ mahasiswa.nama }}</td>
		<td>{{ mahasiswa.jenis_kelamin }}</td>
		<td>{{ mahasiswa.tempat_lahir }}</td>
		<td>{{ mahasiswa.tanggal_lahir }}</td>
		<td>{{ mahasiswa.agama }}</td>
		<td>{{ mahasiswa.alamat }}</td>
		<td style="width: 150px">
	      <button type="button"
	              class="btn btn-warning btn-sm js-update-mahasiswa"
	              data-url="{% url 'dashboard:mahasiswa-ubah' nim_mahasiswa=mahasiswa.nim %}">
	        <span class="glyphicon glyphicon-pencil"></span> Edit
	      </button>
	      <button type="button"
	              class="btn btn-danger btn-sm js-delete-mahasiswa"
	              data-url="{% url 'dashboard:mahasiswa-hapus' nim_mahasiswa=mahasiswa.nim %}">
	        <span class="glyphicon glyphicon-trash"></span> Delete
	      </button>
	    </td>
				   
	</tr>
	{% empty %}
		<tr>
			<td colspan="8" class="text-center bg-warning">Tidak Ada Mahasiswa</td>
		</tr>
{% endfor %}  

dashboard/templates/dashboard/includes/partial_mahasiswa_tambah.html
{% load widget_tweaks %}

<form method="post" action="{% url 'dashboard:mahasiswa-tambah' %}" class="js-mahasiswa-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Tambah Mahasiswa</h4>
  </div>
  <div class="modal-body">
    {% include "dashboard/includes/partial_mahasiswa_form.html" %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Tambah Mahasiswa</button>
  </div>
</form>

dashboard/templates/dashboard/includes/partial_mahasiswa_ubah.html
<form method="post" action="{% url 'dashboard:mahasiswa-ubah' nim_mahasiswa=form.instance.pk %}" class="js-mahasiswa-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Ubah Data Mahasiswa</h4>
  </div>
  <div class="modal-body">
    {% include 'dashboard/includes/partial_mahasiswa_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update Mahasiswa</button>
  </div>
</form>

dashboard/templates/dashboard/mahasiswa_list.html
{% extends "../base.html" %}
{% load static %}

{% block title %}
	{{ title }}
{% endblock title %}


{% block javascript %}
  	<script src="{% static 'dashboard/js/mahasiswa.js' %}"></script>
{% endblock %}


{% block content %}

	<h1 class="page-header text-center"><a href="{% url 'dashboard:mahasiswa-list' %}">{{ title }}</a></h1>

	 <p>
	    <button type="button" class="btn btn-primary js-create-mahasiswa" data-url="{% url 'dashboard:mahasiswa-tambah' %}">
	      <span class="glyphicon glyphicon-plus"></span>
	      Mahasiswa Baru
	    </button>

	    <a href="{% url 'logout' %}" class="btn btn-primary pull-right">
          <span class="glyphicon glyphicon-log-out"></span> Log out
        </a>
	  </p>

	 
	 <form class="form-inline" method="get" action="{% url 'dashboard:mahasiswa-cari' %}">
	 	<div class="form-group mx-sm-3 mb-2">
		    <input type="text" class="form-control" placeholder="Cari Data" name="cari">
 		 </div>
  		
  		<button type="submit" class="btn btn-primary mb-2">cari</button>
	 </form>


	 {% if banyak_data %}
	 	<p>Data : {{ banyak_data }}</p>
	 {% endif %}

	 <table class="table" id="mahasiswa-table">
	    <thead>
	      <tr>
	        <th>Nim</th>
	        <th>Nama</th>
	        <th>Jenis Kelamin</th>
	        <th>Tempat Lahir</th>
	        <th>Tanggal Lahir</th>
	        <th>Agama</th>
	        <th>Alamat</th>
	        <th>Aksi</th>
	      </tr>
	    </thead>
	    
	    <tbody>
	    	{% include "dashboard/includes/partial_mahasiswa_list.html" %}
	    </tbody>
	  </table>

	   <div class="modal fade" id="modal-mahasiswa">
	    <div class="modal-dialog">
	      <div class="modal-content">

	      </div>
	    </div>
	  </div>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
			
		{% endblock title %}
	</title>

	

	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

	<div class="container">
		{% block content %}
			
		{% endblock content %}
	</div>


	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    {% block javascript %}
    	
    {% endblock javascript %}

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{ title }}</title>
	
	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">

	<style type="text/css">
		td {
			padding: 5px;
			margin: 5px;
		}
	</style>

</head>
<body>
	<center>
		<h2>Login User</h2>

		{% if messages %}
			{% for message in messages  %}
				{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
					 <div class="alert alert-success">
  						<strong>Success!</strong> {{message}}
					</div>

				{% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
					 <div class="alert alert-danger alert-dismissible" id="myAlert">
					    <a href="#" class="close">&times;</a>
					    <strong>Failed!</strong> {{message}}
					  </div>
					
				{% endif %}
			{% endfor %}
			
		{% endif %}

		<table>
			<form method="post">
				{% csrf_token %}

				<tr>
					<td>Username</td>
					<td><input type="text" name="username" placeholder="Username"></td>
				</tr>


				<tr>
					<td>Password</td>
					<td><input type="password" name="password" placeholder="Password"></td>
				</tr>


				<tr>
					<td></td>
					<td><input type="submit" value="Login"></td>
				</tr>
				
			</form>
		</table>
	</center>

	

	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

	<script type="text/javascript">
		$(document).ready(function(){
		  $(".close").click(function(){
		    $("#myAlert").alert("close");
		  });
		});
	</script>

</body>
</html>